######################################################################
# Automatically generated by qmake (2.01a) Thu Jan 2 21:23:15 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += widget.h
FORMS += widget.ui
SOURCES += main.cpp widget.cpp
RESOURCES += mp3_src.qrc
